/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 09:28:47 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#include "sm_user_logic.h"
#include "sm_core.h"

void SM_ST_PARA_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: ParA */
    
}

void SM_ST_PARA_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: ParA */
    instance->data.log = (uint32_t)(1U);
}

void SM_ST_PARA_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: ParA */
    
}

void SM_ST_PARB_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: ParB */
    
}

void SM_ST_PARB_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: ParB */
    instance->data.log = (uint32_t)(2U);
}

void SM_ST_PARB_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: ParB */
    
}
