/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-20 11:18:39 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#ifndef SM_CONFIG_H
#define SM_CONFIG_H

#include <stdint.h>
#include <stdbool.h>

/* Constant Limits */
#define SM_NUM_LAYERS 3U
#define SM_NUM_STATES 6U
#define SM_NUM_PARALLEL_REGIONS 1U
#define SM_GENERATOR_VERSION "v3.0 ENGINE"

/* Transition Timer Limits (Named constants to prevent magic numbers) */
/* No timer transitions */

/* Regions */
typedef enum {
    SM_GRP_MAIN,
    SM_GRP_COUNT
} SM_Group_t;

/* States */
typedef enum {
    SM_NODE_INVALID = 0U,
    SM_ST_A,
    SM_ST_B,
    SM_ST_OUT,
    SM_ST_P,
    SM_ST_X,
    SM_ST_Y,
    SM_NODE_ERROR,
    SM_NODE_SAFE
} SM_Node_t;

/* Error Codes */
typedef enum {
    SM_ERR_NONE = 0U,
    SM_ERR_WATCHDOG,
    SM_ERR_SAFETY_VIOLATION,
    SM_ERR_INVALID_STATE,
    SM_ERR_ROM_INTEGRITY,
    SM_ERR_RAM_INTEGRITY
} SM_Error_t;

/* State Indices (derived from unique enum names) */
#define SM_ST_A_IDX 0U
#define SM_ST_B_IDX 1U
#define SM_ST_OUT_IDX 2U
#define SM_ST_P_IDX 3U
#define SM_ST_X_IDX 4U
#define SM_ST_Y_IDX 5U

/* Layer Indices */
#define SM_LYR_LAYERA_IDX 0U
#define SM_LYR_LAYERP_IDX 1U
#define SM_LYR_ROOT_IDX 2U

/* Data Structure */
typedef struct {
    uint32_t log;
    bool t1;
    bool t2;
    bool t3;
    uint32_t state_timer;
} SM_Data_t;

/* Instance Context Structure */
typedef struct {
    SM_Node_t active_states[SM_NUM_LAYERS];
    SM_Node_t history_states[SM_NUM_LAYERS];
    uint32_t state_timers[SM_NUM_STATES];
    bool state_active[SM_NUM_STATES];
    SM_Data_t data;
    SM_Error_t error_status;
} ADIA_Instance_t;

#define SM_TICK_MS (10U)
#define SM_TICK_TOLERANCE (1U)

#endif /* SM_CONFIG_H */