/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-20 11:18:51 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#include "sm_user_logic.h"
#include "sm_core.h"

/* USER CODE BEGIN Includes */
/* USER CODE END Includes */

void SM_ST_S1_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: S1 */
    instance->data.log = (uint32_t)(instance->data.log * 10U + 2U);
}

void SM_ST_S1_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: S1 */
    
}

void SM_ST_S1_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: S1 */
    instance->data.log = (uint32_t)(instance->data.log * 10U + 1U);
}

void SM_ST_S2_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: S2 */
    instance->data.log = (uint32_t)(instance->data.log * 10U + 3U);
}

void SM_ST_S2_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: S2 */
    
}

void SM_ST_S2_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: S2 */
    
}


void SM_NODE_SAFE_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: safety fallback state */
}

void SM_NODE_SAFE_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: safety fallback state */
}

void SM_NODE_SAFE_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: safety fallback state */
}