import type { McalHeaderModel, McalPeripheral } from './mcalTypes.js';

const STATUS_CODES = [
  ['ADIA_MCAL_OK', 0],
  ['ADIA_MCAL_ERROR', 1],
  ['ADIA_MCAL_TIMEOUT', 2],
  ['ADIA_MCAL_NOT_IMPLEMENTED', 3],
  ['ADIA_MCAL_INVALID_CHANNEL', 4],
  ['ADIA_MCAL_INVALID_STATE', 5],
  ['ADIA_MCAL_HEALTH_FAULT', 6],
] as const;

function usedPeripherals(model: McalHeaderModel): McalPeripheral[] {
  const set = new Set<McalPeripheral>();
  for (const ch of model.channels) {
    set.add(ch.peripheral);
  }
  return Array.from(set).sort();
}

function peripheralPrefix(p: McalPeripheral): string {
  return `adia_mcal_${p}`;
}

function channelEnumName(p: McalPeripheral): string {
  return `${peripheralPrefix(p)}_channel_t`;
}

const SAFE_TARGET_ID = /^[a-z][a-z0-9-]{1,63}$/;
const SAFE_CHANNEL_ID = /^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$/;

function cChannelId(id: string): string {
  if (!SAFE_CHANNEL_ID.test(id)) throw new Error(`Invalid MCAL channel identifier: ${id}`);
  return id.replaceAll('-', '_').toUpperCase();
}

export function generateMcalHeader(model: McalHeaderModel): string {
  if (!SAFE_TARGET_ID.test(model.packTargetId)) {
    throw new Error(`Invalid target identifier: ${model.packTargetId}`);
  }
  const normalizedIds = new Set<string>();
  for (const channel of model.channels) {
    const key = `${channel.peripheral}:${cChannelId(channel.channelId)}`;
    if (normalizedIds.has(key)) throw new Error(`Duplicate generated MCAL identifier: ${key}`);
    normalizedIds.add(key);
  }
  const peripherals = usedPeripherals(model);
  const lines: string[] = [];

  lines.push('/* Generated by ADIA. Do not edit manually. */');
  lines.push(`/* Target: ${model.packTargetId} */`);
  lines.push('#ifndef ADIA_MCAL_H');
  lines.push('#define ADIA_MCAL_H');
  lines.push('');
  lines.push('#include <stdbool.h>');
  lines.push('#include <stdint.h>');
  lines.push('#include <stddef.h>');
  lines.push('');
  lines.push('typedef enum {');
  for (const [name, value] of STATUS_CODES) {
    lines.push(`  ${name} = ${value},`);
  }
  lines.push('} adia_mcal_status_t;');
  lines.push('');

  for (const p of peripherals) {
    const channels = model.channels.filter(c => c.peripheral === p);
    const enumName = channelEnumName(p);
    lines.push(`typedef enum ${enumName} {`);
    for (const ch of channels) {
      lines.push(`  ${peripheralPrefix(p).toUpperCase()}_${cChannelId(ch.channelId)},`);
    }
    lines.push(`} ${enumName};`);
    lines.push('');
  }

  lines.push('#ifdef __cplusplus');
  lines.push('extern "C" {');
  lines.push('#endif');
  lines.push('');

  for (const p of peripherals) {
    const prefix = peripheralPrefix(p);
    const enumName = channelEnumName(p);
    lines.push(`adia_mcal_status_t ${prefix}_init(void);`);
    lines.push(`adia_mcal_status_t ${prefix}_deinit(void);`);
    lines.push(`adia_mcal_status_t ${prefix}_health(void);`);
    lines.push(`adia_mcal_status_t ${prefix}_safe_state(void);`);
    const channels = model.channels.filter(channel => channel.peripheral === p);
    const hasInput = channels.some(channel => channel.direction === 'input');
    const hasOutput = channels.some(channel => channel.direction === 'output');
    const isCommunication = p === 'uart' || p === 'spi' || p === 'i2c' || p === 'can';
    if (hasInput && isCommunication) {
      lines.push(`adia_mcal_status_t ${prefix}_read(${enumName} ch, uint8_t *buffer, uint32_t capacity, uint32_t *out_length);`);
    } else if (hasInput) {
      lines.push(`adia_mcal_status_t ${prefix}_read(${enumName} ch, int32_t *out_value);`);
    }
    if (hasOutput && isCommunication) {
      lines.push(`adia_mcal_status_t ${prefix}_write(${enumName} ch, const uint8_t *data, uint32_t length);`);
    } else if (hasOutput) {
      lines.push(`adia_mcal_status_t ${prefix}_write(${enumName} ch, int32_t value);`);
    }
    lines.push('');
  }

  lines.push('#ifdef __cplusplus');
  lines.push('}');
  lines.push('#endif');
  lines.push('');
  lines.push('#endif /* ADIA_MCAL_H */');
  lines.push('');

  return lines.join('\n');
}
