/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 09:28:47 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#include "sm_user_logic.h"
#include "sm_core.h"

void SM_ST_A_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: A */
    
}

void SM_ST_A_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: A */
    
}

void SM_ST_A_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: A */
    
}

void SM_ST_B_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: B */
    
}

void SM_ST_B_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: B */
    
}

void SM_ST_B_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: B */
    
}

void SM_ST_OUT_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: Out */
    
}

void SM_ST_OUT_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: Out */
    
}

void SM_ST_OUT_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: Out */
    
}

void SM_ST_P_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: P */
    
}

void SM_ST_P_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: P */
    
}

void SM_ST_P_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: P */
    
}

void SM_ST_X_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: X */
    
}

void SM_ST_X_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: X */
    
}

void SM_ST_X_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: X */
    
}

void SM_ST_Y_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: Y */
    
}

void SM_ST_Y_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: Y */
    
}

void SM_ST_Y_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: Y */
    
}
