/* Generated by ADIA. Do not edit manually. */
/* Target: atmega2560 */
#ifndef ADIA_MCAL_H
#define ADIA_MCAL_H

#include <stdbool.h>
#include <stdint.h>

typedef enum {
  ADIA_MCAL_OK = 0,
  ADIA_MCAL_ERROR = 1,
  ADIA_MCAL_TIMEOUT = 2,
  ADIA_MCAL_NOT_IMPLEMENTED = 3,
  ADIA_MCAL_INVALID_CHANNEL = 4,
  ADIA_MCAL_INVALID_STATE = 5,
  ADIA_MCAL_HEALTH_FAULT = 6,
} adia_mcal_status_t;

typedef enum adia_mcal_gpio_channel_t {
  ADIA_MCAL_GPIO_9B4C84B5_D1BA_413C_83BC_E11F567B19CF,
  ADIA_MCAL_GPIO_F0B3089A_1426_4D8A_ADD0_6A146A51378E,
} adia_mcal_gpio_channel_t;

#ifdef __cplusplus
extern "C" {
#endif

adia_mcal_status_t adia_mcal_gpio_init(void);
adia_mcal_status_t adia_mcal_gpio_deinit(void);
adia_mcal_status_t adia_mcal_gpio_health(void);
adia_mcal_status_t adia_mcal_gpio_safe_state(void);
adia_mcal_status_t adia_mcal_gpio_read(adia_mcal_gpio_channel_t ch, int32_t *out_value);
adia_mcal_status_t adia_mcal_gpio_write(adia_mcal_gpio_channel_t ch, int32_t value);

#ifdef __cplusplus
}
#endif

#endif /* ADIA_MCAL_H */
