/* ============================================================= */
/*  SAFETY CRITICAL CODE - DO NOT EDIT MANUALLY                  */
/*  Generated by ADIA Tool | Version: v2.4 ENGINE                 */
/*  Compliance: IEC 60730 Class B / ISO 13849                    */
/*  Timestamp: 2026-06-14T13:22:47.256Z                       */
/* ============================================================= */

#include "sm_core.h"
#include "sm_safety.h"
#include "sm_user_logic.h"

/* Forward declarations of internal static helpers */
static void SM_Exit_State(ADIA_Instance_t* instance, SM_Node_t state);
static void SM_Enter_State(ADIA_Instance_t* instance, SM_Node_t state, bool use_history);
static void SM_Enter_Layer_0(ADIA_Instance_t* instance, bool use_history);
static void SM_Step_Layer_0(ADIA_Instance_t* instance, uint32_t delta_ms);

SM_Node_t SM_GetActive(const ADIA_Instance_t* instance, SM_Group_t g) {
    SM_Node_t active = SM_NODE_INVALID;
    if ((uint32_t)g < SM_NUM_LAYERS) {
        active = instance->active_states[(uint32_t)g];
    }
    return active;
}

SM_Error_t SM_GetError(const ADIA_Instance_t* instance) {
    return instance->error_status;
}

void SM_Init(ADIA_Instance_t* instance) {
    uint32_t i;
    for (i = 0U; i < SM_NUM_LAYERS; i++) {
        instance->active_states[i] = SM_NODE_INVALID;
        instance->history_states[i] = SM_NODE_INVALID;
    }
    for (i = 0U; i < SM_NUM_STATES; i++) {
        instance->state_timers[i] = 0U;
    }
    instance->data.counter = 0;
    instance->data.flag = false;
    instance->data.value = 0.0;
    instance->data.state_timer = 0U;
    instance->error_status = SM_ERR_NONE;
    SM_Reset(instance);
}

void SM_Reset(ADIA_Instance_t* instance) {
    uint32_t i;
    for (i = 0U; i < SM_NUM_LAYERS; i++) {
        instance->active_states[i] = SM_NODE_INVALID;
    }
    instance->error_status = SM_ERR_NONE;
    SM_Enter_Layer_0(instance, false);
}

void SM_Step(ADIA_Instance_t* instance, uint32_t delta_ms) {
    SM_Watchdog_Kick(instance);
    SM_Safety_Check(instance);
    if (instance->error_status != SM_ERR_NONE) {
        if (instance->error_status == SM_ERR_SAFETY_VIOLATION ||
            instance->error_status == SM_ERR_RAM_INTEGRITY ||
            instance->error_status == SM_ERR_ROM_INTEGRITY) {
            uint32_t i;
            for (i = 0U; i < SM_NUM_LAYERS; i++) {
                instance->active_states[i] = SM_NODE_SAFE;
            }
            return;
        }
        uint32_t i;
        for (i = 0U; i < SM_NUM_LAYERS; i++) {
            instance->active_states[i] = SM_NODE_ERROR;
        }
        return;
    }
    if (instance->data.state_timer + delta_ms < instance->data.state_timer) instance->data.state_timer = UINT32_MAX;
    else instance->data.state_timer += delta_ms;

    /* Increment state timers */
    if (instance->active_states[0U] == SM_ST_LOW_POWER) {
        if (instance->state_timers[0U] + delta_ms < instance->state_timers[0U]) {
            instance->state_timers[0U] = 4294967295U;
        } else {
            instance->state_timers[0U] += delta_ms;
        }
    }
    if (instance->active_states[0U] == SM_ST_STATE_1) {
        if (instance->state_timers[1U] + delta_ms < instance->state_timers[1U]) {
            instance->state_timers[1U] = 4294967295U;
        } else {
            instance->state_timers[1U] += delta_ms;
        }
    }
    if (instance->active_states[0U] == SM_ST_STATE_2) {
        if (instance->state_timers[2U] + delta_ms < instance->state_timers[2U]) {
            instance->state_timers[2U] = 4294967295U;
        } else {
            instance->state_timers[2U] += delta_ms;
        }
    }

    /* Step root layer */
    SM_Step_Layer_0(instance, delta_ms);
}

/* Helper Functions Implementation */
static void SM_Exit_State(ADIA_Instance_t* instance, SM_Node_t state) {
    switch (state) {
        case SM_ST_LOW_POWER:
            SM_ST_LOW_POWER_Exit(instance);
            instance->state_timers[0U] = 0U;
            instance->active_states[0U] = SM_NODE_INVALID;
            break;
        case SM_ST_STATE_1:
            SM_ST_STATE_1_Exit(instance);
            instance->state_timers[1U] = 0U;
            instance->active_states[0U] = SM_NODE_INVALID;
            break;
        case SM_ST_STATE_2:
            SM_ST_STATE_2_Exit(instance);
            instance->state_timers[2U] = 0U;
            instance->active_states[0U] = SM_NODE_INVALID;
            break;
        default:
            break;
    }
}


static void SM_Enter_State(ADIA_Instance_t* instance, SM_Node_t state, bool use_history) {
    switch (state) {
        case SM_ST_LOW_POWER:
            instance->active_states[0U] = state;
            instance->state_timers[0U] = 0U;
            SM_ST_LOW_POWER_Entry(instance);
            break;
        case SM_ST_STATE_1:
            instance->active_states[0U] = state;
            instance->state_timers[1U] = 0U;
            SM_ST_STATE_1_Entry(instance);
            break;
        case SM_ST_STATE_2:
            instance->active_states[0U] = state;
            instance->state_timers[2U] = 0U;
            SM_ST_STATE_2_Entry(instance);
            break;
        default:
            break;
    }
}


static void SM_Enter_Layer_0(ADIA_Instance_t* instance, bool use_history) {
    if (use_history && (instance->history_states[0U] != SM_NODE_INVALID)) {
        SM_Enter_State(instance, instance->history_states[0U], true);
    } else {
        SM_Enter_State(instance, SM_ST_STATE_1, false);
    }
}


static void SM_Step_Layer_0(ADIA_Instance_t* instance, uint32_t delta_ms) {
    switch (instance->active_states[0U]) {
        case SM_ST_STATE_1:
            /* Evaluate Outgoing Transitions */
            if (true) {
                SM_Exit_State(instance, SM_ST_STATE_1);
                SM_Enter_State(instance, SM_ST_STATE_2, false);
                return;
            }
            else { /* MISRA 15.7 */ }
            /* Run During Actions */
            SM_ST_STATE_1_During(instance, delta_ms);
            break;
        case SM_ST_STATE_2:
            /* Evaluate Outgoing Transitions */
            if (true) {
                SM_Exit_State(instance, SM_ST_STATE_2);
                SM_Enter_State(instance, SM_ST_LOW_POWER, false);
                return;
            }
            else { /* MISRA 15.7 */ }
            /* Run During Actions */
            SM_ST_STATE_2_During(instance, delta_ms);
            break;
        case SM_ST_LOW_POWER:
            /* Evaluate Outgoing Transitions */
            /* Run During Actions */
            SM_ST_LOW_POWER_During(instance, delta_ms);
            break;
        default:
            break;
    }
}

