/* ============================================================= */
/*  SAFETY CRITICAL CODE - DO NOT EDIT MANUALLY                  */
/*  Generated by ADIA Tool | Version: v2.4 ENGINE                 */
/*  Compliance: IEC 60730 Class B / ISO 13849                    */
/*  Timestamp: 2026-06-14T13:22:47.256Z                       */
/* ============================================================= */

#ifndef SM_CONFIG_H
#define SM_CONFIG_H

#include <stdint.h>
#include <stdbool.h>

/* Constant Limits */
#define SM_NUM_LAYERS 1U
#define SM_NUM_STATES 3U

/* Regions */
typedef enum {
    SM_GRP_MAIN,
    SM_GRP_COUNT
} SM_Group_t;

/* States */
typedef enum {
    SM_NODE_INVALID = 0U,
    SM_ST_LOW_POWER,
    SM_ST_STATE_1,
    SM_ST_STATE_2,
    SM_NODE_ERROR,
    SM_NODE_SAFE
} SM_Node_t;

/* Error Codes */
typedef enum {
    SM_ERR_NONE = 0U,
    SM_ERR_WATCHDOG,
    SM_ERR_SAFETY_VIOLATION,
    SM_ERR_INVALID_STATE,
    SM_ERR_ROM_INTEGRITY,
    SM_ERR_RAM_INTEGRITY
} SM_Error_t;

/* State Indices */
#define SM_ST_LOW_POWER_IDX 0U
#define SM_ST_STATE_1_IDX 1U
#define SM_ST_STATE_2_IDX 2U

/* Layer Indices */
#define SM_LYR_ROOT_IDX 0U

/* Data Structure */
typedef struct {
    int32_t counter;
    bool flag;
    float value;
    uint32_t state_timer;
} SM_Data_t;

/* Instance Context Structure */
typedef struct {
    SM_Node_t active_states[SM_NUM_LAYERS];
    SM_Node_t history_states[SM_NUM_LAYERS];
    uint32_t state_timers[SM_NUM_STATES];
    SM_Data_t data;
    SM_Error_t error_status;
} ADIA_Instance_t;

/* Legacy Compatibility Constants instead of macros */
static const uint32_t SM_TICK_MS = 500U;

#endif /* SM_CONFIG_H */