/* ============================================================= */
/*  SAFETY CRITICAL CODE - DO NOT EDIT MANUALLY                  */
/*  Generated by ADIA Tool | Version: v2.4 ENGINE                 */
/*  Compliance: IEC 60730 Class B / ISO 13849                    */
/*  Timestamp: 2026-06-30T14:07:55.857Z                       */
/* ============================================================= */

#ifndef SM_CORE_H
#define SM_CORE_H

#include "sm_config.h"

void SM_Init(ADIA_Instance_t* instance);
void SM_Reset(ADIA_Instance_t* instance);
void SM_Step(ADIA_Instance_t* instance, uint32_t delta_ms);
SM_Node_t SM_GetActive(const ADIA_Instance_t* instance, SM_Group_t g);
SM_Error_t SM_GetError(const ADIA_Instance_t* instance);

/* Deprecated API for direct access */
static inline SM_Data_t* SM_Data_Legacy(ADIA_Instance_t* instance) {
    return &instance->data;
}

#endif /* SM_CORE_H */