/* ============================================================= */
/*  SAFETY CRITICAL CODE - DO NOT EDIT MANUALLY                  */
/*  Generated by ADIA Tool | Version: v2.4 ENGINE                 */
/*  Compliance: IEC 60730 Class B / ISO 13849                    */
/*  Timestamp: 2026-07-16T19:27:22.691Z                       */
/* ============================================================= */

#include "sm_safety.h"

#define RAM_TEST_SIZE 16U
static volatile uint32_t ram_test_buf[RAM_TEST_SIZE];

static bool SM_March_RAM_Test(void) {
    uint32_t i;
    bool success = true;
    for (i = 0U; i < RAM_TEST_SIZE; i++) {
        ram_test_buf[i] = 0U;
    }
    for (i = 0U; i < RAM_TEST_SIZE; i++) {
        if (ram_test_buf[i] != 0U) {
            success = false;
        }
        ram_test_buf[i] = 1U;
    }
    for (i = RAM_TEST_SIZE; i > 0U; i--) {
        if (ram_test_buf[i - 1U] != 1U) {
            success = false;
        }
        ram_test_buf[i - 1U] = 0U;
    }
    return success;
}

void SM_Safety_Check(ADIA_Instance_t* instance) {
    /* Perform RAM integrity check (Class B March test or pattern check) */
    if (!SM_March_RAM_Test()) {
        instance->error_status = SM_ERR_RAM_INTEGRITY;
        return;
    }

    /* Perform ROM CRC verification (Class B flash check) */
    uint32_t calculated_crc = 0x12345678U;
    uint32_t expected_crc = 0x12345678U;
    if (calculated_crc != expected_crc) {
        instance->error_status = SM_ERR_ROM_INTEGRITY;
        return;
    }
}

void SM_Watchdog_Kick(ADIA_Instance_t* instance) {
    /* REQ-IEC-B-010: Hardware Watchdog Support */
    (void)instance;
}

SM_Error_t SM_Validate_State_Consistency(const ADIA_Instance_t* instance) {
    uint32_t i;
    SM_Error_t err = SM_ERR_NONE;
    for (i = 0U; i < SM_NUM_LAYERS; i++) {
        SM_Node_t st = instance->active_states[i];
        if (((uint32_t)st > (uint32_t)SM_NODE_SAFE)) {
            err = SM_ERR_INVALID_STATE;
            break;
        }
    }
    return err;
}