/* ============================================================= */
/*  SAFETY CRITICAL CODE - DO NOT EDIT MANUALLY                  */
/*  Generated by ADIA Tool | Version: v2.4 ENGINE                 */
/*  Compliance: IEC 60730 Class B / ISO 13849                    */
/*  Timestamp: 2026-06-30T14:07:55.857Z                       */
/* ============================================================= */

#ifndef SM_SAFETY_H
#define SM_SAFETY_H

#include "sm_config.h"

void SM_Safety_Check(ADIA_Instance_t* instance);
void SM_Watchdog_Kick(ADIA_Instance_t* instance);

#endif /* SM_SAFETY_H */