/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 14:27:18 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#ifndef SM_USER_LOGIC_H
#define SM_USER_LOGIC_H

#include "sm_config.h"

/* State Action Prototypes */
void SM_ST_LOW_POWER_Entry(ADIA_Instance_t* instance);
void SM_ST_LOW_POWER_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_LOW_POWER_Exit(ADIA_Instance_t* instance);
void SM_ST_STATE_1_Entry(ADIA_Instance_t* instance);
void SM_ST_STATE_1_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_STATE_1_Exit(ADIA_Instance_t* instance);
void SM_ST_STATE_2_Entry(ADIA_Instance_t* instance);
void SM_ST_STATE_2_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_STATE_2_Exit(ADIA_Instance_t* instance);

#endif /* SM_USER_LOGIC_H */