/* ============================================================= */
/* File generated by ADIA Code Generator v2.4 ENGINE              */
/* Model: ADIA State Machine | 2026-07-17 09:17:35 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Compliance: MISRA C:2012 / IEC 60730 Class B / ISO 13849      */
/* ============================================================= */

#ifndef SM_USER_LOGIC_H
#define SM_USER_LOGIC_H

#include "sm_config.h"

/* State Action Prototypes */
void SM_ST_LOW_POWER_Entry(ADIA_Instance_t* instance);
void SM_ST_LOW_POWER_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_LOW_POWER_Exit(ADIA_Instance_t* instance);
void SM_ST_STATE_1_Entry(ADIA_Instance_t* instance);
void SM_ST_STATE_1_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_STATE_1_Exit(ADIA_Instance_t* instance);
void SM_ST_STATE_2_Entry(ADIA_Instance_t* instance);
void SM_ST_STATE_2_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_STATE_2_Exit(ADIA_Instance_t* instance);

#endif /* SM_USER_LOGIC_H */