/* ============================================================= */
/*  SAFETY CRITICAL CODE - DO NOT EDIT MANUALLY                  */
/*  Generated by ADIA Tool | Version: v2.4 ENGINE                 */
/*  Compliance: IEC 60730 Class B / ISO 13849                    */
/*  Timestamp: 2026-06-30T14:07:55.857Z                       */
/* ============================================================= */

#ifndef SM_USER_LOGIC_H
#define SM_USER_LOGIC_H

#include "sm_config.h"

/* State Action Prototypes */
void SM_ST_LOW_POWER_Entry(ADIA_Instance_t* instance);
void SM_ST_LOW_POWER_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_LOW_POWER_Exit(ADIA_Instance_t* instance);
void SM_ST_STATE_1_Entry(ADIA_Instance_t* instance);
void SM_ST_STATE_1_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_STATE_1_Exit(ADIA_Instance_t* instance);
void SM_ST_STATE_2_Entry(ADIA_Instance_t* instance);
void SM_ST_STATE_2_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_STATE_2_Exit(ADIA_Instance_t* instance);

#endif /* SM_USER_LOGIC_H */