/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 14:27:18 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#include "sm_user_logic.h"
#include "sm_core.h"

void SM_ST_LOW_POWER_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: Low_Power */
    /* Low Power Mode */
}

void SM_ST_LOW_POWER_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: Low_Power */
    
}

void SM_ST_LOW_POWER_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: Low_Power */
    
}

void SM_ST_STATE_1_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: State_1 */
    
}

void SM_ST_STATE_1_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: State_1 */
    
}

void SM_ST_STATE_1_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: State_1 */
    
}

void SM_ST_STATE_2_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: State_2 */
    
}

void SM_ST_STATE_2_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: State_2 */
    
}

void SM_ST_STATE_2_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: State_2 */
    
}
