/* ============================================================= */
/*  SAFETY CRITICAL CODE - DO NOT EDIT MANUALLY                  */
/*  Generated by ADIA Tool | Version: v2.4 ENGINE                 */
/*  Compliance: IEC 60730 Class B / ISO 13849                    */
/*  Timestamp: 2026-06-30T14:07:55.857Z                       */
/* ============================================================= */

#include "sm_user_logic.h"
#include "sm_core.h"

void SM_ST_LOW_POWER_Entry(ADIA_Instance_t* instance) {
    /* Entry: Low_Power */
    /* Low Power Mode */
}

void SM_ST_LOW_POWER_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    /* During: Low_Power */
    
}

void SM_ST_LOW_POWER_Exit(ADIA_Instance_t* instance) {
    /* Exit: Low_Power */
    
}

void SM_ST_STATE_1_Entry(ADIA_Instance_t* instance) {
    /* Entry: State_1 */
    
}

void SM_ST_STATE_1_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    /* During: State_1 */
    
}

void SM_ST_STATE_1_Exit(ADIA_Instance_t* instance) {
    /* Exit: State_1 */
    
}

void SM_ST_STATE_2_Entry(ADIA_Instance_t* instance) {
    /* Entry: State_2 */
    
}

void SM_ST_STATE_2_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    /* During: State_2 */
    
}

void SM_ST_STATE_2_Exit(ADIA_Instance_t* instance) {
    /* Exit: State_2 */
    
}
