/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-20 11:18:04 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#ifndef SM_USER_LOGIC_H
#define SM_USER_LOGIC_H

#include "sm_config.h"

/* State Action Prototypes */
void SM_ST_C_Entry(ADIA_Instance_t* instance);
void SM_ST_C_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_C_Exit(ADIA_Instance_t* instance);
void SM_ST_D_Entry(ADIA_Instance_t* instance);
void SM_ST_D_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_D_Exit(ADIA_Instance_t* instance);
void SM_ST_P_Entry(ADIA_Instance_t* instance);
void SM_ST_P_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_P_Exit(ADIA_Instance_t* instance);
void SM_ST_Q_Entry(ADIA_Instance_t* instance);
void SM_ST_Q_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_Q_Exit(ADIA_Instance_t* instance);
/* Safety fallback state actions */
void SM_NODE_SAFE_Entry(ADIA_Instance_t* instance);
void SM_NODE_SAFE_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_NODE_SAFE_Exit(ADIA_Instance_t* instance);

#endif /* SM_USER_LOGIC_H */