/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 09:30:16 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

/* System headers */
#include <stdint.h>
#include <stdbool.h>

/* Project headers */
#include "sm_safety.h"
#include "mcal_dio.h"

#define RAM_TEST_SIZE 16U
static volatile uint32_t ram_test_buf[RAM_TEST_SIZE];

/**
 * @brief Performs a Class B March RAM test on a test buffer.
 * @return bool True if RAM test succeeded, false otherwise
 */
static bool SM_March_RAM_Test(void) {
    uint32_t i;       /* MISRA 8.7: declared at top of function */
    bool success = true;
    for (i = 0U; i < RAM_TEST_SIZE; i++) {
        ram_test_buf[i] = 0U;
    }
    for (i = 0U; i < RAM_TEST_SIZE; i++) {
        if (ram_test_buf[i] != 0U) {
            success = false;
        }
        ram_test_buf[i] = 1U;
    }
    /* Reverse March test: count down explicitly using bounded positive subtraction to satisfy MISRA 18.1 array boundary safety */
    for (i = 0U; i < RAM_TEST_SIZE; i++) {
        uint32_t rev_idx = (RAM_TEST_SIZE - 1U) - i;
        if (ram_test_buf[rev_idx] != 1U) {
            success = false;
        }
        ram_test_buf[rev_idx] = 0U;
    }
    return success;
}

/**
 * @brief Executes safety checks (RAM March test; ROM CRC hook documented inline).
 * @param instance Pointer to state machine context
 */
void SM_Safety_Check(ADIA_Instance_t* instance) {
    /* Perform RAM integrity check (Class B March test) */
    if (!SM_March_RAM_Test()) {
        instance->error_status = SM_ERR_RAM_INTEGRITY;
        return;
    }

    /* ROM integrity verification is target-specific and intentionally not
     * fabricated here. To enable it, integrate a CRC32 routine and a
     * linker-placed reference CRC for your target (IEC 60730 Class B),
     * then set instance->error_status = SM_ERR_ROM_INTEGRITY on mismatch. */
}

/**
 * @brief Feeds/kicks the hardware watchdog timer.
 * @param instance Pointer to state machine context
 */
void SM_Watchdog_Kick(ADIA_Instance_t* instance) {
    /* REQ-IEC-B-010: Hardware Watchdog Support */
    (void)instance;
    /* Kick/feed physical watchdog via MCAL layer */
    MCAL_Watchdog_Kick();
}

/**
 * @brief Validates the active states array consistency.
 * @param instance Pointer to state machine context
 * @return SM_Error_t Validation result error status
 */
SM_Error_t SM_Validate_State_Consistency(const ADIA_Instance_t* instance) {
    uint32_t sm_iter;   /* MISRA 8.7: declared at top of function */
    SM_Node_t st;
    SM_Error_t err = SM_ERR_NONE;
    for (sm_iter = 0U; sm_iter < SM_NUM_LAYERS; sm_iter++) {
        st = instance->active_states[sm_iter];
        if ((uint32_t)st > (uint32_t)SM_NODE_SAFE) {
            err = SM_ERR_INVALID_STATE;
            break;
        }
    }
    return err;
}