/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 09:30:16 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#include "sm_user_logic.h"
#include "sm_core.h"

void SM_ST_A_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: A */
    
}

void SM_ST_A_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: A */
    
}

void SM_ST_A_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: A */
    
}

void SM_ST_B_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: B */
    
}

void SM_ST_B_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: B */
    
}

void SM_ST_B_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: B */
    
}

void SM_ST_C_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: C */
    
}

void SM_ST_C_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: C */
    
}

void SM_ST_C_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: C */
    
}
