/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-20 11:19:15 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#include "sm_user_logic.h"
#include "sm_core.h"

/* USER CODE BEGIN Includes */
/* USER CODE END Includes */

void SM_ST_RUN_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: Run */
    
}

void SM_ST_RUN_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: Run */
    
}

void SM_ST_RUN_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: Run */
    instance->data.log = (uint32_t)(instance->data.log * 10U + 1U);
}

void SM_ST_SAFE_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: Safe */
    instance->data.log = (uint32_t)(instance->data.log * 10U + 2U);
}

void SM_ST_SAFE_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: Safe */
    
}

void SM_ST_SAFE_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: Safe */
    
}


void SM_NODE_SAFE_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: safety fallback state */
}

void SM_NODE_SAFE_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: safety fallback state */
}

void SM_NODE_SAFE_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: safety fallback state */
}