export interface BlockDimensions { width: number; height: number }

export const BLOCK_DIMENSIONS: Record<string, BlockDimensions> = {
  ground: { width: 40, height: 30 },
  ma_selector: { width: 40, height: 60 },
  resistor: { width: 60, height: 30 },
  capacitor: { width: 60, height: 30 },
  inductor: { width: 60, height: 30 },
  diode: { width: 60, height: 30 },
  memristor: { width: 60, height: 30 },
  infinite_resistance: { width: 60, height: 30 },
  ps_to_sim: { width: 60, height: 30 },
  sim_to_ps: { width: 60, height: 30 },
  opamp: { width: 60, height: 40 },
  switch: { width: 60, height: 40 },
  variable_resistor: { width: 60, height: 40 },
  thermal_resistor: { width: 60, height: 40 },
  upper_heater: { width: 60, height: 40 },
  gas_pipe: { width: 60, height: 40 },
  gas_fixed_res: { width: 60, height: 40 },
  lever: { width: 60, height: 40 },
  rot_ref: { width: 60, height: 40 },
  rot_spring: { width: 60, height: 40 },
  rot_damper: { width: 60, height: 40 },
  rot_friction: { width: 60, height: 40 },
  rot_hard_stop: { width: 60, height: 40 },
  trans_ref: { width: 60, height: 40 },
  trans_spring: { width: 60, height: 40 },
  trans_damper: { width: 60, height: 40 },
  trans_friction: { width: 60, height: 40 },
  trans_hard_stop: { width: 60, height: 40 },
  ma_properties: { width: 60, height: 40 },
  conductive_heat: { width: 60, height: 40 },
  convective_heat: { width: 60, height: 40 },
  radiative_heat: { width: 60, height: 40 },
  ps_gain: { width: 60, height: 40 },
  ps_integrator: { width: 60, height: 40 },
  ps_transfer_fcn: { width: 60, height: 40 },
  ps_rms: { width: 60, height: 40 },
  ps_pi_ctrl: { width: 60, height: 40 },
  ps_pid_ctrl: { width: 60, height: 40 },
  ps_sum: { width: 40, height: 40 },
  ps_ramp: { width: 40, height: 40 },
  solver_config: { width: 60, height: 40 },
  scope: { width: 60, height: 40 },
  ps_math: { width: 50, height: 50 },
  ps_lookup_1d: { width: 50, height: 50 },
  ps_lookup_2d: { width: 50, height: 50 },
  ps_add: { width: 40, height: 40 },
  ps_subtract: { width: 40, height: 40 },
  ps_product: { width: 40, height: 40 },
  ps_divide: { width: 40, height: 40 },
  ps_abs: { width: 40, height: 40 },
  ps_deadzone: { width: 40, height: 40 },
  ps_saturation: { width: 40, height: 40 },
  ps_dead_zone: { width: 40, height: 40 },
  ps_constant: { width: 40, height: 40 },
  ps_sine: { width: 40, height: 40 },
  ps_step: { width: 40, height: 40 },
  ps_term: { width: 40, height: 40 },
  conn_label: { width: 40, height: 40 },
  ps_demux: { width: 40, height: 60 },
  ps_demux_3: { width: 40, height: 60 },
  microwave_inverter: { width: 70, height: 50 },
  pwm_3ph_2level: { width: 80, height: 60 },
  pwm_3ph_3level: { width: 80, height: 60 },
  microwave_cavity: { width: 80, height: 60 },
  lms_adaptive_filter: { width: 80, height: 60 },
  im_foc_ctrl: { width: 80, height: 80 },
  im_scalar_ctrl: { width: 80, height: 80 },
  washing_basket: { width: 80, height: 80 },
  neural_neuron_learning: { width: 80, height: 80 },
  rl_q_learning_controller: { width: 80, height: 80 },
  cavity: { width: 80, height: 60 },
  ps_const: { width: 40, height: 40 },
  ps_dead: { width: 40, height: 40 },
  ps_sat: { width: 40, height: 40 },
  ps_tf: { width: 60, height: 40 },
  pid_ctrl: { width: 60, height: 40 },
  ma_props: { width: 60, height: 40 },
  subsystem: { width: 70, height: 60 },
  inport: { width: 60, height: 40 },
  outport: { width: 60, height: 40 },
  eye: { width: 60, height: 40 },
  wind: { width: 60, height: 40 },
  heater: { width: 60, height: 40 },
  check_valve: { width: 60, height: 40 },
  relief_valve: { width: 60, height: 40 },
  orifice: { width: 60, height: 40 },
  nozzle: { width: 60, height: 40 },
  fluid_res: { width: 60, height: 30 },
  gas_res: { width: 60, height: 30 },
  inverter: { width: 60, height: 40 },
  minus: { width: 40, height: 40 },
  zap: { width: 40, height: 40 },
  rot_motion: { width: 60, height: 40 },
  trans_motion: { width: 60, height: 40 }
};

export const DEFAULT_DIMENSIONS: BlockDimensions = { width: 60, height: 60 };

export function getBlockDimensions(type: string | undefined): BlockDimensions {
  if (!type) return DEFAULT_DIMENSIONS;
  return BLOCK_DIMENSIONS[type] || DEFAULT_DIMENSIONS;
}
