/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 09:29:00 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#include "sm_user_logic.h"
#include "sm_core.h"

void SM_ST_C_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: C */
    
}

void SM_ST_C_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: C */
    
}

void SM_ST_C_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: C */
    instance->data.log = (uint32_t)(instance->data.log * 10U + 1U);
}

void SM_ST_D_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: D */
    instance->data.log = (uint32_t)(instance->data.log * 10U + 7U);
}

void SM_ST_D_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: D */
    
}

void SM_ST_D_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: D */
    
}

void SM_ST_P_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: P */
    instance->data.log = (uint32_t)(instance->data.log * 10U + 6U);
}

void SM_ST_P_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: P */
    
}

void SM_ST_P_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: P */
    instance->data.log = (uint32_t)(instance->data.log * 10U + 2U);
}

void SM_ST_Q_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: Q */
    instance->data.log = (uint32_t)(instance->data.log * 10U + 4U);
}

void SM_ST_Q_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: Q */
    
}

void SM_ST_Q_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: Q */
    instance->data.log = (uint32_t)(instance->data.log * 10U + 5U);
}
