/* ============================================================= */
/* File generated by ADIA Code Generator v2.4 ENGINE              */
/* Model: ADIA State Machine | 2026-07-16 20:54:21 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Compliance: MISRA C:2012 / IEC 60730 Class B / ISO 13849      */
/* ============================================================= */

#ifndef SM_SAFETY_H
#define SM_SAFETY_H

/* System headers */
#include <stdint.h>
#include <stdbool.h>

/* Project headers */
#include "sm_config.h"

/* Safety API */
void SM_Safety_Check(ADIA_Instance_t* instance);
void SM_Watchdog_Kick(ADIA_Instance_t* instance);
SM_Error_t SM_Validate_State_Consistency(const ADIA_Instance_t* instance);

#endif /* SM_SAFETY_H */