/* ============================================================= */
/* File generated by ADIA Code Generator v2.4 ENGINE              */
/* Model: ADIA State Machine | 2026-07-17 09:01:26 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Compliance: MISRA C:2012 / IEC 60730 Class B / ISO 13849      */
/* ============================================================= */

#ifndef SM_USER_LOGIC_H
#define SM_USER_LOGIC_H

#include "sm_config.h"

/* State Action Prototypes */
void SM_ST_ACTIVE_Entry(ADIA_Instance_t* instance);
void SM_ST_ACTIVE_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_ACTIVE_Exit(ADIA_Instance_t* instance);
void SM_ST_IDLE_Entry(ADIA_Instance_t* instance);
void SM_ST_IDLE_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_IDLE_Exit(ADIA_Instance_t* instance);

#endif /* SM_USER_LOGIC_H */