/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-20 11:19:23 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#include "sm_user_logic.h"
#include "sm_core.h"

/* USER CODE BEGIN Includes */
/* USER CODE END Includes */

void SM_ST_ACTIVE_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: Active */
    instance->data.is_active = true;
}

void SM_ST_ACTIVE_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: Active */
    instance->data.counter = (uint16_t)(instance->data.counter + 1U);
}

void SM_ST_ACTIVE_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: Active */
    instance->data.is_active = false;
}

void SM_ST_IDLE_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: Idle */
    instance->data.counter = (uint16_t)(0U);
}

void SM_ST_IDLE_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: Idle */
    instance->data.sensor_val = (float)(1.2f);
}

void SM_ST_IDLE_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: Idle */
    
}


void SM_NODE_SAFE_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: safety fallback state */
}

void SM_NODE_SAFE_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: safety fallback state */
}

void SM_NODE_SAFE_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: safety fallback state */
}