import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const repositoryRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '..',
);
const entryPoint = resolve(
  repositoryRoot,
  'src/utils/stateMachine/smStandaloneRuntime.ts',
);
const generatedFile = resolve(
  repositoryRoot,
  'src/generated/stateMachineRuntimeBundle.ts',
);

const result = await build({
  absWorkingDir: repositoryRoot,
  entryPoints: [entryPoint],
  bundle: true,
  charset: 'utf8',
  format: 'iife',
  globalName: 'ADIAStateMachineRuntime',
  legalComments: 'none',
  platform: 'browser',
  target: ['es2020'],
  write: false,
});

if (result.outputFiles.length !== 1) {
  throw new Error(
    `Expected one standalone runtime output, received ${result.outputFiles.length}.`,
  );
}

const runtimeBundle = `${result.outputFiles[0].text
  .replace(/\r\n/g, '\n')
  .trimEnd()}\n`;
const generatedSource = [
  '// This file is generated by scripts/build_state_machine_runtime.ts.',
  '// Do not edit it directly.',
  `export const STATE_MACHINE_RUNTIME_BUNDLE = ${JSON.stringify(runtimeBundle)};`,
  '',
].join('\n');

await mkdir(dirname(generatedFile), { recursive: true });
await writeFile(generatedFile, generatedSource, 'utf8');
