/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-20 11:19:21 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#ifndef MCAL_DIO_H
#define MCAL_DIO_H

#include <stdint.h>
#include <stdbool.h>

/* USER CODE BEGIN McalDio_Top */
/* USER CODE END McalDio_Top */

/* Microcontroller Abstraction Layer (MCAL) DIO Port/Pin Definition Stub */
#define MCAL_PIN_INPUT_0   0U
#define MCAL_PIN_INPUT_1   1U
#define MCAL_PIN_OUTPUT_0  2U
#define MCAL_PIN_OUTPUT_1  3U


/**
 * @brief Reads the state of a physical Digital Input channel.
 * @param channel Channel pin index
 * @return bool Pin level state (true/false)
 */
static inline bool MCAL_Dio_ReadChannel(uint32_t channel) {
    (void)channel;
    /* USER CODE BEGIN ReadChannel */
    return false; /* Default stub/simulation value */
    /* USER CODE END ReadChannel */
}

/**
 * @brief Writes the state of a physical Digital Output channel.
 * @param channel Channel pin index
 * @param level   Pin level state to write
 */
static inline void MCAL_Dio_WriteChannel(uint32_t channel, bool level) {
    (void)channel;
    (void)level;
    /* USER CODE BEGIN WriteChannel */
    /* USER CODE END WriteChannel */
}

/**
 * @brief Feeds/Kicks the physical hardware watchdog timer.
 */
static inline void MCAL_Watchdog_Kick(void) {
    /* USER CODE BEGIN Watchdog_Kick */
    /* USER CODE END Watchdog_Kick */
}

#endif /* MCAL_DIO_H */