/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 09:31:00 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

/* System headers */
#include <stdint.h>
#include <stdbool.h>

/* Project headers */
#include "sm_core.h"
#include "sm_safety.h"
#include "sm_user_logic.h"
#include "mcal_dio.h"

/* Forward declarations of public API functions for C99 compliance */
void SM_Init(ADIA_Instance_t* instance);
void SM_Reset(ADIA_Instance_t* instance);
void SM_Step(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_Sync_IO(ADIA_Instance_t* instance);
SM_Node_t SM_GetActive(const ADIA_Instance_t* instance, SM_Group_t g);
SM_Error_t SM_GetError(const ADIA_Instance_t* instance);

/* Forward declarations of internal static helpers */
static void SM_Exit_State(ADIA_Instance_t* instance, SM_Node_t state);
static void SM_Enter_State_Shallow(ADIA_Instance_t* instance, SM_Node_t state);
static void SM_Enter_State(ADIA_Instance_t* instance, SM_Node_t state, bool use_history);
static void SM_Enter_Layer_0(ADIA_Instance_t* instance, bool use_history);
static void SM_Step_Layer_0(ADIA_Instance_t* instance, uint32_t delta_ms);

/**
 * @brief Returns the active state node of the specified region group.
 * @param instance Pointer to state machine context
 * @param g        Region group index
 * @return SM_Node_t The currently active state
 */
SM_Node_t SM_GetActive(const ADIA_Instance_t* instance, SM_Group_t g) {
    SM_Node_t active = SM_NODE_INVALID;
    switch (g) {
        case SM_GRP_MAIN:
            active = instance->active_states[0U];
            break;
        default:
            break;
    }
    return active;
}

/**
 * @brief Queries the error status of the state machine.
 * @param instance Pointer to state machine context
 * @return SM_Error_t Current error status
 */
SM_Error_t SM_GetError(const ADIA_Instance_t* instance) {
    return instance->error_status;
}

/**
 * @brief Initializes the state machine context and registers default/initial values.
 * @param instance Pointer to state machine context
 */
void SM_Init(ADIA_Instance_t* instance) {
    uint32_t sm_iter;  /* MISRA 8.7: declared at top of function */
    (void)&SM_Exit_State;
    for (sm_iter = 0U; sm_iter < SM_NUM_LAYERS; sm_iter++) {
        instance->active_states[sm_iter]  = SM_NODE_INVALID;
        instance->history_states[sm_iter] = SM_NODE_INVALID;
    }
    for (sm_iter = 0U; sm_iter < SM_NUM_STATES; sm_iter++) {
        instance->state_timers[sm_iter] = 0U;
        instance->state_active[sm_iter] = false;
    }
    instance->data.log = 0U;
    instance->data.t1 = false;
    instance->data.t2 = false;
    instance->data.t3 = false;
    instance->data.state_timer = 0U;
    instance->error_status = SM_ERR_NONE;
    SM_Reset(instance);
}

/**
 * @brief Resets the state machine, fully reinitializing all runtime arrays.
 * @param instance Pointer to state machine context
 */
void SM_Reset(ADIA_Instance_t* instance) {
    uint32_t sm_iter;  /* MISRA 8.7: declared at top of function */
    for (sm_iter = 0U; sm_iter < SM_NUM_LAYERS; sm_iter++) {
        instance->active_states[sm_iter] = SM_NODE_INVALID;
        instance->history_states[sm_iter] = SM_NODE_INVALID;
    }
    for (sm_iter = 0U; sm_iter < SM_NUM_STATES; sm_iter++) {
        instance->state_timers[sm_iter] = 0U;
        instance->state_active[sm_iter] = false;
    }
    instance->error_status = SM_ERR_NONE;
    SM_Enter_Layer_0(instance, false);
}

/**
 * @brief Steps the state machine: runs safety checks (if enabled), increments timers, and processes transitions.
 * @param instance Pointer to state machine context
 * @param delta_ms Execution tick period in milliseconds
 */
void SM_Step(ADIA_Instance_t* instance, uint32_t delta_ms) {
    /* MISRA 8.7: All loop variables declared at top of function */
    uint32_t sm_iter;
    (void)sm_iter;
    /* MISRA 12.4/15.6: overflow check without wrap-around, braced if body */
    if (delta_ms > (UINT32_MAX - instance->data.state_timer)) {
        instance->data.state_timer = UINT32_MAX;
    } else {
        instance->data.state_timer += delta_ms;
    }

    /* Increment state timers */
    if (instance->state_active[0U]) {
        if (delta_ms > (UINT32_MAX - instance->state_timers[0U])) {
            instance->state_timers[0U] = UINT32_MAX;
        } else {
            instance->state_timers[0U] += delta_ms;
        }
    }
    if (instance->state_active[1U]) {
        if (delta_ms > (UINT32_MAX - instance->state_timers[1U])) {
            instance->state_timers[1U] = UINT32_MAX;
        } else {
            instance->state_timers[1U] += delta_ms;
        }
    }

    /* Step root layer */
    SM_Step_Layer_0(instance, delta_ms);
}

/**
 * @brief Synchronizes state machine variables with MCAL hardware channels.
 * @param instance Pointer to state machine context
 */
void SM_Sync_IO(ADIA_Instance_t* instance) {
    /* MCAL-to-SM Input Signal Binding */
    instance->data.log = (uint32_t)MCAL_Dio_ReadChannel(MCAL_PIN_INPUT_0);

    /* SM-to-MCAL Output Signal Binding */
    MCAL_Dio_WriteChannel(MCAL_PIN_OUTPUT_0, instance->data.t1);

}

/* Helper Functions Implementation */
/**
 * @brief Exits the specified state and recursively exits active sub-states.
 * @req REQ-HSM-040 Hierarchical State Exit
 * @param instance Pointer to state machine context
 * @param state State node to exit
 */
static void SM_Exit_State(ADIA_Instance_t* instance, SM_Node_t state) {
    switch (state) {
        case SM_ST_A:
            SM_ST_A_Exit(instance);
            instance->state_active[0U] = false;
            instance->state_timers[0U] = 0U;
            instance->active_states[0U] = SM_NODE_INVALID;
            break;
        case SM_ST_B:
            SM_ST_B_Exit(instance);
            instance->state_active[1U] = false;
            instance->state_timers[1U] = 0U;
            instance->active_states[0U] = SM_NODE_INVALID;
            break;
        default:
            break;
    }
}


/**
 * @brief Enters a single state without descending into its child layers.
 * @param instance Pointer to state machine context
 * @param state State node to enter
 */
static void SM_Enter_State_Shallow(ADIA_Instance_t* instance, SM_Node_t state) {
    switch (state) {
        case SM_ST_A:
            instance->active_states[0U] = state;
            instance->state_active[0U] = true;
            instance->state_timers[0U] = 0U;
            SM_ST_A_Entry(instance);
            break;
        case SM_ST_B:
            instance->active_states[0U] = state;
            instance->state_active[1U] = true;
            instance->state_timers[1U] = 0U;
            SM_ST_B_Entry(instance);
            break;
        default:
            break;
    }
}


/**
 * @brief Enters the specified state, sets its active flag, and recursively enters child layers.
 * @req REQ-HSM-030 Hierarchical State Entry
 * @param instance Pointer to state machine context
 * @param state State node to enter
 * @param use_history True to restore sub-state history
 */
static void SM_Enter_State(ADIA_Instance_t* instance, SM_Node_t state, bool use_history) {
    (void)use_history;
    SM_Enter_State_Shallow(instance, state);
    switch (state) {
        default:
            break;
    }
}


/**
 * @brief Enters layer 0 and initializes default states or junctions.
 * @param instance Pointer to state machine context
 * @param use_history True to restore history states
 */
static void SM_Enter_Layer_0(ADIA_Instance_t* instance, bool use_history) {
    if (use_history && (instance->history_states[0U] != SM_NODE_INVALID)) {
        SM_Enter_State(instance, instance->history_states[0U], false);
    } else {
        SM_Enter_State(instance, SM_ST_A, false);
    }
}


/**
 * @brief Evaluates transitions and executes during actions for layer 0.
 * @param instance Pointer to state machine context
 * @param delta_ms Execution tick period in milliseconds
 */
static void SM_Step_Layer_0(ADIA_Instance_t* instance, uint32_t delta_ms) {
    switch (instance->active_states[0U]) {
        case SM_ST_A:
            /* Evaluate Outgoing Transitions */
            if ((instance->data.t1)) {
                SM_Exit_State(instance, SM_ST_A);
                SM_Enter_State(instance, SM_ST_B, false);
                return;
            }
            else { /* MISRA 15.7 */ }
            /* Run During Actions */
            SM_ST_A_During(instance, delta_ms);
            break;
        case SM_ST_B:
            /* Evaluate Outgoing Transitions */
            /* Run During Actions */
            SM_ST_B_During(instance, delta_ms);
            break;
        default:
            break;
    }
}

