/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-20 11:19:21 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#ifndef SM_USER_LOGIC_H
#define SM_USER_LOGIC_H

#include "sm_config.h"

/* State Action Prototypes */
void SM_ST_A_Entry(ADIA_Instance_t* instance);
void SM_ST_A_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_A_Exit(ADIA_Instance_t* instance);
void SM_ST_B_Entry(ADIA_Instance_t* instance);
void SM_ST_B_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_B_Exit(ADIA_Instance_t* instance);
/* Safety fallback state actions */
void SM_NODE_SAFE_Entry(ADIA_Instance_t* instance);
void SM_NODE_SAFE_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_NODE_SAFE_Exit(ADIA_Instance_t* instance);

#endif /* SM_USER_LOGIC_H */