/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 09:30:46 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#ifndef SM_SAFETY_H
#define SM_SAFETY_H

/* System headers */
#include <stdint.h>
#include <stdbool.h>

/* Project headers */
#include "sm_config.h"

/* Safety API */
void SM_Safety_Check(ADIA_Instance_t* instance);
void SM_Watchdog_Kick(ADIA_Instance_t* instance);
SM_Error_t SM_Validate_State_Consistency(const ADIA_Instance_t* instance);

#endif /* SM_SAFETY_H */