/* ============================================================= */
/* File generated by ADIA Code Generator v2.4 ENGINE              */
/* Model: ADIA State Machine | 2026-07-17 09:01:26 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Compliance: MISRA C:2012 / IEC 60730 Class B / ISO 13849      */
/* ============================================================= */

#ifndef SM_CONFIG_H
#define SM_CONFIG_H

#include <stdint.h>
#include <stdbool.h>

/* Constant Limits */
#define SM_NUM_LAYERS 1U
#define SM_NUM_STATES 1U
#define SM_NUM_PARALLEL_REGIONS 1U
#define SM_GENERATOR_VERSION "3.0"

/* Transition Timer Limits (Named constants to prevent magic numbers) */
/* No timer transitions */

/* Regions */
typedef enum {
    SM_GRP_MAIN,
    SM_GRP_COUNT
} SM_Group_t;

/* States */
typedef enum {
    SM_NODE_INVALID = 0U,
    SM_ST_IDLE,
    SM_NODE_ERROR,
    SM_NODE_SAFE
} SM_Node_t;

/* Error Codes */
typedef enum {
    SM_ERR_NONE = 0U,
    SM_ERR_WATCHDOG,
    SM_ERR_SAFETY_VIOLATION,
    SM_ERR_INVALID_STATE,
    SM_ERR_ROM_INTEGRITY,
    SM_ERR_RAM_INTEGRITY
} SM_Error_t;

/* State Indices */
#define SM_ST_IDLE_IDX 0U

/* Layer Indices */
#define SM_LYR_ROOT_IDX 0U

/* Data Structure */
typedef struct {
    uint16_t counter;
    bool is_active;
    float sensor_val;
    float block2_state;
    uint32_t state_timer;
} SM_Data_t;

/* Instance Context Structure */
typedef struct {
    SM_Node_t active_states[SM_NUM_LAYERS];
    SM_Node_t history_states[SM_NUM_LAYERS];
    uint32_t state_timers[SM_NUM_STATES];
    bool state_active[SM_NUM_STATES];
    SM_Data_t data;
    SM_Error_t error_status;
} ADIA_Instance_t;

#define SM_TICK_MS (10U)

#endif /* SM_CONFIG_H */