/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 09:34:03 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#ifndef SM_CORE_H
#define SM_CORE_H

/* System headers */
#include <stdint.h>
#include <stdbool.h>

/* Project headers */
#include "sm_config.h"

/* Public API */
void SM_Init(ADIA_Instance_t* instance);
void SM_Reset(ADIA_Instance_t* instance);
void SM_Step(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_Sync_IO(ADIA_Instance_t* instance);
SM_Node_t SM_GetActive(const ADIA_Instance_t* instance, SM_Group_t g);
SM_Error_t SM_GetError(const ADIA_Instance_t* instance);

/* Legacy API - returns const pointer to data struct (deprecated, use SM_Init/SM_Step) */
static inline const SM_Data_t* SM_Data_Legacy(const ADIA_Instance_t* instance) {
    return &instance->data;
}

#endif /* SM_CORE_H */