/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 09:34:03 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#include "sm_user_logic.h"
#include "sm_core.h"

void SM_ST_IDLE_Entry(ADIA_Instance_t* instance) {
    (void)instance;
    /* Entry: Idle */
    instance->data.counter = (uint16_t)(0U);
}

void SM_ST_IDLE_During(ADIA_Instance_t* instance, uint32_t delta_ms) {
    (void)instance;
    (void)delta_ms;
    /* During: Idle */
    instance->data.sensor_val = (float)(1.2f);
    /* Co-Model Step */
    SM_ST_IDLE_XBridges_Step(instance, 0.0100f);
}

void SM_ST_IDLE_Exit(ADIA_Instance_t* instance) {
    (void)instance;
    /* Exit: Idle */
    
}

/* Generated X-Bridges logic for Idle */
void SM_ST_IDLE_XBridges_Step(ADIA_Instance_t* instance, float delta_s) {
    (void)instance;
    (void)delta_s;
    /* Local Signal Variables */
    float block1_out0 = 0.0f;
    float block2_out0 = 0.0f;

    /* Sync SM -> Model */

    /* Block Execution Loop */
    /* Block: Constant (block1) */
    block1_out0 = 5.0000f;
    /* Block: Integrator (block2) */
    instance->data.idle_block2_state += block1_out0 * delta_s;
    block2_out0 = instance->data.idle_block2_state;

    /* Sync Model -> SM */
    instance->data.sensor_val = (float)(block2_out0);
}
