/* ============================================================= */
/* File generated by ADIA Code Generator v3.0 ENGINE              */
/* Model: ADIA State Machine | 2026-07-18 09:34:03 UTC */
/* DO NOT EDIT MANUALLY - Changes will be overwritten            */
/* Coding guidelines: MISRA C:2012 (advisory) / ISO C99          */
/* ============================================================= */

#ifndef SM_USER_LOGIC_H
#define SM_USER_LOGIC_H

#include "sm_config.h"

/* State Action Prototypes */
void SM_ST_IDLE_Entry(ADIA_Instance_t* instance);
void SM_ST_IDLE_During(ADIA_Instance_t* instance, uint32_t delta_ms);
void SM_ST_IDLE_Exit(ADIA_Instance_t* instance);
void SM_ST_IDLE_XBridges_Step(ADIA_Instance_t* instance, float delta_s);

#endif /* SM_USER_LOGIC_H */